# Site settings
title: nerith
email: csbit32@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about FOSS software development and Computer Science. Powered by
  <a href='http://jekyllrb.com'>Jekyll</a> and
  <a href='http://getbootstrap.com'>Bootstrap</a>.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username:
github_username:  nerith
content_license: <p>
                 <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0"
                 src="https://i.creativecommons.org/l/by-nc/4.0/80x15.png" /></a><br />This work is licensed under a <a rel="license"
                 href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.
                 </p>
# Build settings
markdown: kramdown
